### ISSUE TITLE
面板是好面板，但是什么是管理密钥

### ISSUE THREAD

**Issue by JohnsonRan** [akile-network/akile_monitor#1]
![image](https://github.com/user-attachments/assets/0cc31855-2380-4cf4-8870-d4ade9e2e62f)
`auth_secret`和`hook_token`都不是（

**Comment by JohnsonRan** [comment]
![image](https://github.com/user-attachments/assets/fc4d1105-538e-4755-9585-a364be293108)
啊 看了眼控制台

**Comment by Miuss** [comment]
> ![image](https://private-user-images.githubusercontent.com/89735151/391976960-fc4d1105-538e-4755-9585-a364be293108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzI2NTcsIm5iZiI6MTczMzIzMjM1NywicGF0aCI6Ii84OTczNTE1MS8zOTE5NzY5NjAtZmM0ZDExMDUtNTM4ZS00NzU1LTk1ODUtYTM2NGJlMjkzMTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzY3YjgzYWYwNzZiZTM2OGI2OTQwNDU0ZjgxYzY4MDE3NWVlNTdkOTJmMDYzMWUxOWJiMjBiNzMxNjc0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r5nVAwetXCs15B4IFrTnSOVbJDdfxH7jfY_UjsbL4uA) 啊 看了眼控制台

已经修复这个问题，前端bug，重新下载一下构建后的
https://github.com/akile-network/akile_monitor_fe/releases/tag/v0.0.1

**Comment by JohnsonRan** [comment]
可以了 谢谢佬
