### ISSUE TITLE
WebSocket连接失败

### ISSUE THREAD

**Issue by aisuyi065** [akile-network/akile_monitor#8]
root@debian:~# ps -fp 302
UID          PID    PPID  C STIME TTY          TIME CMD
root         302       1  0 02:55 ?        00:00:00 /etc/ak_monitor/ak_monitor
root@debian:~# ss -tulnp | grep :3000
tcp   LISTEN 0      4096               *:3000             *:*    users:(("ak_monitor",pid=302,fd=7),("ak_monitor",pid=302,fd=6))
root@debian:~#

**Comment by Miuss** [comment]
前端config.json有改地址吗？

**Comment by aisuyi065** [comment]
> 前端config.json有改地址吗？

改了
另外修改端口好像不生效，还是原来的3000

**Comment by Miuss** [comment]
我们这边测试是好的，你仔细检查一下配置文件config.json
